name: Node CI JS

on:
  push:
    branches:
      - "*"
      - "*/*"

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!(contains(github.actor, 'process-engine-ci') || contains(github.actor, 'admin'))"

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        version: 12.x

    - name: 'Install Dependencies'
      working-directory: ./javascript
      run: npm ci

    - name: 'Prepare Version'
      working-directory: ./javascript
      run: ./node_modules/.bin/ci_tools prepare-version --allow-dirty-workdir

    - name: 'Build Sources'
      working-directory: ./javascript
      run: npm run build

    - name: 'Publish Version'
      working-directory: ./javascript
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: ./node_modules/.bin/ci_tools publish-npm-package --create-tag-from-branch-name

